# Generated by Django 4.2.20 on 2025-03-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(max_length=10, unique=True)),
                ('firstname', models.CharField(max_length=50)),
                ('secondname', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phonenumber', models.CharField(max_length=15)),
                ('company', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
