# Generated by Django 4.2.20 on 2025-03-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='email',
            field=models.EmailField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
