# Generated by Django 4.2.20 on 2025-03-24 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_vendorprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('second_name', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=15)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.TextField()),
                ('company', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='VendorProfile',
        ),
    ]
