# Generated by Django 4.2.20 on 2025-03-25 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_vendor_options_tourpackage_packageimages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Tour_Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_title', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('place_image', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(help_text='Duration in days')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('top_package', models.BooleanField(default=False)),
                ('budget_friendly', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('auto_expire', models.BooleanField(default=True)),
                ('bookings', models.IntegerField(default=0)),
                ('approved', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vendor')),
            ],
            options={
                'verbose_name': 'Tour package',
                'verbose_name_plural': 'Tour packages',
            },
        ),
        migrations.RemoveField(
            model_name='packagefacilities',
            name='package',
        ),
        migrations.RemoveField(
            model_name='packageimages',
            name='package',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='PackageFacilities',
        ),
        migrations.DeleteModel(
            name='PackageImages',
        ),
        migrations.DeleteModel(
            name='TourPackage',
        ),
    ]
